apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-credentials
  labels:
    app.kubernetes.io/part-of: data-loader-app
stringData:
  MYSQL_ROOT_PASSWORD: "kjytfcryegbfy8679hcsrdfgcvdu"
  MYSQL_PASSWORD: "ghjsdcbxyf67rgevtc76"
type: Opaque