apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-db
    app.kubernetes.io/part-of: data-loader-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi