apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-db
    app.kubernetes.io/part-of: data-loader-app
spec:
  selector:
    app.kubernetes.io/instance: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306