apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-api-deployment
  labels:
    app.kubernetes.io/name: fastapi-api
    app.kubernetes.io/instance: mysql-api
    app.kubernetes.io/part-of: data-loader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-api
        app.kubernetes.io/instance: mysql-api
        app.kubernetes.io/part-of: data-loader-app
    spec:
      containers:
        - name: fastapi-container
          image: "docker.io/YOUR_DOCKERHUB_USERNAME/data-loader-service:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql-db-service"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-credentials
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"