apiVersion: v1
kind: Service
metadata:
  name: mysql-api-service
  labels:
    app: mysql-api
spec:
  selector:
    app: mysql-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP